services:
  cm:
    build:
      args:
        SPS_IMAGE: ${SITECORE_MODULE_REGISTRY}sitecore-sps-integration-xm1-assets:${SPS_ASSET_VERSION}
        SPS_ASSETS_IMAGE: ${REGISTRY}${COMPOSE_PROJECT_NAME}-sps-assets:${VERSION:-latest}
    environment:
      SITECORE_PUBLISHING_SERVICE_URL: "http://sps"
  sps-init:
    isolation: ${ISOLATION}
    image: ${SITECORE_MODULE_REGISTRY}sitecore-sps:${SPS_VERSION}
    environment:
      SITECORE_PUBLISHING__CONNECTIONSTRINGS__CORE: Data Source=${SQL_SERVER};Initial Catalog=Sitecore.Core;User ID=${SQL_SA_LOGIN};Password=${SQL_SA_PASSWORD};MultipleActiveResultSets=True
      SITECORE_PUBLISHING__CONNECTIONSTRINGS__MASTER: Data Source=${SQL_SERVER};Initial Catalog=Sitecore.Master;User ID=${SQL_SA_LOGIN};Password=${SQL_SA_PASSWORD};MultipleActiveResultSets=True
      SITECORE_PUBLISHING__CONNECTIONSTRINGS__WEB: Data Source=${SQL_SERVER};Initial Catalog=Sitecore.Web;User ID=${SQL_SA_LOGIN};Password=${SQL_SA_PASSWORD};MultipleActiveResultSets=True
      SITECORE_PUBLISHING__CONNECTIONSTRINGS__SERVICE: Data Source=${SQL_SERVER};Initial Catalog=Sitecore.Master;User ID=${SQL_SA_LOGIN};Password=${SQL_SA_PASSWORD};MultipleActiveResultSets=True
    volumes:
      - ${SITECORE_LICENSE_PATH}:C:/sps/sitecoreruntime:ro
    command: schema upgrade --force
    depends_on:
      mssql-init:
        condition: service_healthy
  sps:
    image: ${SITECORE_MODULE_REGISTRY}sitecore-sps:${SPS_VERSION}
    environment:
      ASPNETCORE_URLS: "http://*:80"
      SITECORE_PUBLISHING__CONNECTIONSTRINGS__CORE: Data Source=${SQL_SERVER};Initial Catalog=Sitecore.Core;User ID=${SQL_SA_LOGIN};Password=${SQL_SA_PASSWORD};MultipleActiveResultSets=True
      SITECORE_PUBLISHING__CONNECTIONSTRINGS__MASTER: Data Source=${SQL_SERVER};Initial Catalog=Sitecore.Master;User ID=${SQL_SA_LOGIN};Password=${SQL_SA_PASSWORD};MultipleActiveResultSets=True
      SITECORE_PUBLISHING__CONNECTIONSTRINGS__WEB: Data Source=${SQL_SERVER};Initial Catalog=Sitecore.Web;User ID=${SQL_SA_LOGIN};Password=${SQL_SA_PASSWORD};MultipleActiveResultSets=True
      SITECORE_PUBLISHING__CONNECTIONSTRINGS__SERVICE: Data Source=${SQL_SERVER};Initial Catalog=Sitecore.Master;User ID=${SQL_SA_LOGIN};Password=${SQL_SA_PASSWORD};MultipleActiveResultSets=True
    ports:
      - "80"
    volumes:
      - ${SITECORE_LICENSE_PATH}:C:/sps/sitecoreruntime:ro
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/healthz/live"]
      timeout: 300s
    depends_on:
      sps-init:
        condition: service_completed_successfully